## Code 102 
[Growth mindset](https://shiloh206.github.io/reading-notes/)
[Markdown](https://shiloh206.github.io/reading-notes/coder'scomputer)
[Coder's Computer](https://shiloh206.github.io/reading-notes/coder'scomputer)
[Gitt]((https://shiloh206.github.io/reading-notes/gitt)
[HTML](https://shiloh206.github.io/reading-notes/html)
[CSS](https://shiloh206.github.io/reading-notes/css)
[JavaScript)(https://shiloh206.github.io/reading-notes/javascript)
[More JavaScript](https://shiloh206.github.io/reading-notes/javascript-07)
[Operators & Loops](https://shiloh206.github.io/reading-notes/loops)
